### ISSUE TITLE
skinned mesh renderer support??

### ISSUE THREAD

**Issue by davoodkharmanzar** [reinsteam/Unity-FrustumCulling#1]
hi,
and thanks for this awesome WOW project :]

but does it support any type of renderers like as Skinned mesh?

and can you provide an general script to just drag and drop it to the main camera to working automatically on any scene?

also, does it support on Android too?

**Comment by reinsteam** [comment]
- It is possible to use any renderer including skinned mesh renderer; the latter might require to recompute its axis-aligned bounding box every frame. The sample uses pre-cached bounding boxes for the sake of simplicity but gives an option to regenerate them.
- `FrustumCullSetupScript.cs` is already a drag-n-drop script which is attached to the main camera in a test scene.
- The sample was not tested on Android but should work after disabling the native plugin.
